version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: estimai-backend
    environment:
      ARTIFACT_DIR: /app/backend/artifacts
      LOG_LEVEL: INFO
      CORS_ORIGINS: http://localhost:8080
      COMMIT_SHA: ${COMMIT_SHA:-dev}
    ports:
      - "8000:8000"
    volumes:
      # host artifacts -> container artifacts (persist across restarts)
      - ./backend/artifacts:/app/backend/artifacts
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: estimai-frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  # (named volume optional; we're using bind mount above for clarity)
